" 基礎設定
set nocompatible
filetype plugin on
set laststatus=2
set noswapfile
set nobackup

" クリップボード使用可能にする
set clipboard=unnamed,autoselect

" 編集
set tabstop=2
set softtabstop=2
set shiftwidth=2
set noexpandtab
set autoindent
set nonu
set ambiwidth=double
set encoding=utf8
set fileencoding=utf8
set fileencodings=ucs-bom,utf-8,iso-2022-jp-3,iso-2022-jp,eucjp-ms,euc-jisx0213,euc-jp,sjis,cp932
set backspace=indent,start,eol
set wildmenu
set showcmd
syntax on

" Commandモードを便利に
cnoremap <C-a> <S-Left>
cnoremap <C-e> <S-Right>

" Insertモードを便利に
inoremap <C-h> <Left>
inoremap <C-j> <Down>
inoremap <C-k> <Up>
inoremap <C-l> <Right>
inoremap jj <Esc>
inoremap <C-o> <C-x><C-o>

" 外部設定の読み込み
if filereadable(expand('~/vimfiles/vimrc.plug'))
	source ~/vimfiles/vimrc.plug
endif
if filereadable(expand('~/vimfiles/vimrc.leader'))
	source ~/vimfiles/vimrc.leader
endif
if filereadable(expand('~/vimfiles/vimrc.term'))
	" ターミナル操作関連。現状空
	source ~/vimfiles/vimrc.term
endif

" マウス(terminalっぽくする)
set mouse=a

winpos -1865 9
let g:did_install_default_menus = 1

" 日本語対応系
set iminsert=0
set imsearch=0
set noimcmdline
set display+=lastline

" netrw(開発用の鍵で認証する)
let g:netrw_scp_cmd="C:\\msys64\\usr\\bin\\scp.exe -i C:\\Users\\aizawa\\.ssh\\id_rsa"
let g:netrw_list_cmd="C:\\msys64\\usr\\bin\\ssh.exe -i C:\\Users\\aizawa\\.ssh\\id_rsa HOSTNAME ls -Fa"
